Tests/98/sp 1 write unit test for popupdialog component
Space2Study-UA-1156/Client-01 pull request #126
Opened 2024-04-29 11:37 UTC by holus-bolus

Created the unit tests for the Pop up dialog component

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/104f0f88-e98c-44d1-8012-3acb5dad169c)

2024-04-29 13:23 UTC, OlhaOvsiienko approved these changes

2024-04-29 17:55 UTC, YaroslavChuiko approved these changes

2024-04-30 06:55 UTC, khytrykv approved these changes

2024-05-01 07:02 UTC, vlad-khrychov requested changes

2024-05-01 07:02 UTC, vlad-khrychov commented on src/components/popup-dialog/PopupDialog.jsx
> +
```suggestion
```

2024-05-01 07:02 UTC, vlad-khrychov commented on src/components/popup-dialog/PopupDialog.jsx
> +        <IconButton aria-label='Close' onClick={handleClose} sx={styles.icon}>
Why are you adding functionality when the task was only about the test?

2024-05-01 07:02 UTC, vlad-khrychov commented on tests/unit/components/popup-dialog/PopupDialog.spec.jsx
Mock also hook `useBreakpoints`

2024-05-01 07:02 UTC, vlad-khrychov commented on tests/unit/components/popup-dialog/PopupDialog.spec.jsx
> +    vi.advanceTimersByTime(5000)
I like this solution, share experience with teammates if they need to test functions with delay.

2024-05-01 07:10 UTC, holus-bolus commented on src/components/popup-dialog/PopupDialog.jsx
> +        <IconButton aria-label='Close' onClick={handleClose} sx={styles.icon}>
@vlad-khrychov because I needed to top up the coverage, I wanted it to be 100%, without this test it's about 92%

2024-05-01 07:16 UTC, holus-bolus commented on tests/unit/components/popup-dialog/PopupDialog.spec.jsx
Done

2024-05-01 15:59 UTC, vlad-khrychov approved these changes

2024-05-01 15:59 UTC, vlad-khrychov commented on src/components/popup-dialog/PopupDialog.jsx
> +        <IconButton aria-label='Close' onClick={handleClose} sx={styles.icon}>
Ok, we can use it, but next time try to find another way

2024-05-01 16:01 UTC, merged