unit test for AppHeader component
Space2Study-UA-1156/Client-01 pull request #127
Opened 2024-04-29 11:38 UTC by voloshkin-v

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/56509285/cc46c9bf-91ed-448d-9349-8ac0d0af4289)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/56509285/faca648d-5918-47c7-8d4b-7de86374b4e2)

2024-04-29 13:09 UTC, holus-bolus approved these changes

2024-04-29 13:10 UTC, OlhaOvsiienko approved these changes

2024-04-29 17:58 UTC, YaroslavChuiko approved these changes

2024-04-29 18:51 UTC, vlad-khrychov requested changes
Mock <NavBar /> because it is our own component that has already been (or will be) tested separately.

2024-05-01 16:01 UTC, voloshkin-v commented
> Mock `<NavBar />` because it is our own component that has already been (or will be) tested separately.

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/56509285/8c6391d6-dbe3-45b3-ac18-86509f015b06)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/56509285/f84b831f-b495-47b5-a269-c2be64b204a0)

2024-05-06 11:11 UTC, vlad-khrychov approved these changes

2024-05-06 13:49 UTC, merged