unit test for "AppTextField" component
Space2Study-UA-1156/Client-01 pull request #130
Opened 2024-04-29 17:51 UTC by YaroslavChuiko

Unit test for "AppTextField" component
implemented scenaries:
- [ ]  Should be rendered input with error message

**Current coverage:**
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/8f7bc3bf-8023-4880-9191-7033487396de)

2024-04-29 19:10 UTC, OlhaOvsiienko approved these changes

2024-04-30 05:05 UTC, holus-bolus approved these changes
Good job

2024-04-30 08:03 UTC, YaroslavLys approved these changes

2024-04-30 17:39 UTC, khytrykv approved these changes

2024-05-01 07:08 UTC, vlad-khrychov requested changes

2024-05-01 07:08 UTC, vlad-khrychov commented on tests/unit/components/app-text-field/AppTextField.spec.jsx
Add test `should render input without error message` for improving **branches**.

2024-05-01 18:01 UTC, closed without merging