Added tests for GeneralInfoStep container
Space2Study-UA-1156/Client-01 pull request #133
Opened 2024-04-30 07:51 UTC by YaroslavLys

<img width="1505" alt="image" src="https://github.com/Space2Study-UA-1156/Client-01/assets/74725159/5dcde247-48f1-40bf-affc-98a2bdc4ccc7">

2024-04-30 08:06 UTC, OlhaOvsiienko approved these changes

2024-04-30 08:41 UTC, khytrykv approved these changes

2024-04-30 09:27 UTC, holus-bolus approved these changes

2024-04-30 13:23 UTC, YaroslavChuiko approved these changes

2024-05-01 07:15 UTC, vlad-khrychov requested changes

2024-05-01 07:15 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
> +import { screen } from '@testing-library/react'
Import libraries first
```suggestion
import { screen } from '@testing-library/react'
import { renderWithProviders } from '~tests/test-utils'
import GeneralInfoStep from '~/containers/tutor-home-page/general-info-step/GeneralInfoStep'

```

2024-05-01 07:15 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
> +    renderWithProviders(<GeneralInfoStep btnsBox={buttons} />)
Use `beforeEach` if renders are the same.

2024-05-01 16:00 UTC, vlad-khrychov approved these changes

2024-05-01 17:35 UTC, merged