Write unit test for "AppPopover" component
Space2Study-UA-1156/Client-01 pull request #135
Opened 2024-04-30 09:59 UTC by YaroslavChuiko

Unit test for "AppPopover" component
implemented scenarios:
- [ ] Imitate click on the button and open popover
- [ ] button should not be visible after click
- [ ] button should be visible after click

**Current coverage:**
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/05a74934-85ab-4b8b-a1f8-a6dd9869d5b6)

2024-04-30 10:18 UTC, holus-bolus approved these changes

2024-04-30 17:15 UTC, YaroslavLys approved these changes

2024-04-30 17:38 UTC, khytrykv approved these changes

2024-05-01 07:22 UTC, vlad-khrychov requested changes

2024-05-01 07:22 UTC, vlad-khrychov commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +import { expect, it } from 'vitest'
```suggestion
```

2024-05-01 07:22 UTC, vlad-khrychov commented on tests/unit/components/app-popover/AppPopover.spec.jsx
I think that function `closePopover ` is not called. So call event `close` on `Popover` to cover it.

2024-05-01 10:25 UTC, YaroslavChuiko commented
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/9becd499-f219-4875-b3b0-0ab6ec3b0eb2)

2024-05-01 15:21 UTC, vlad-khrychov approved these changes

2024-05-01 15:39 UTC, merged