Add tests for Loader
Space2Study-UA-1156/Client-01 pull request #150
Opened 2024-04-30 15:56 UTC by khytrykv

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/15dda893-8394-4dcb-81a0-f5adec680a41)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/f4c7135a-dc97-4cf6-9103-70c5a1e0214d)

2024-04-30 16:04 UTC, holus-bolus approved these changes

2024-04-30 16:07 UTC, YaroslavChuiko commented
I think the path should be `tests/unit/components/loader/Loader.spec.jsx` same as the path to the Loader component
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/823c229b-a06f-49cf-97e8-1cf9d2b87a43)

2024-04-30 16:21 UTC, khytrykv commented
> I think the path should be `tests/unit/components/loader/Loader.spec.jsx` same as the path to the Loader component ![image](https://private-user-images.githubusercontent.com/32570823/326889855-823c229b-a06f-49cf-97e8-1cf9d2b87a43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTQzNTEsIm5iZiI6MTcxNDQ5NDA1MSwicGF0aCI6Ii8zMjU3MDgyMy8zMjY4ODk4NTUtODIzYzIyOWItYTA2Zi00OWNmLTk3ZTgtMWNmOWQyYjg3YTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE2MjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkODk5MDljZmJlMzE0NTc1MDM4MDU4Nzk5NWZkNzE5ZWRiMWJjMzgwOTJmYTQ5NjNkNDBlNmNjY2I0ZmMyNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C5CTSmC2kjhvNXb7QWa8DaXY3rnSaIwUQqlwtRqXe-A)

Fixed

2024-04-30 16:21 UTC, YaroslavChuiko approved these changes

2024-04-30 16:43 UTC, voloshkin-v approved these changes

2024-05-01 07:05 UTC, vlad-khrychov requested changes

2024-05-01 07:05 UTC, vlad-khrychov commented on tests/unit/components/loader/Loader.spec.jsx
Mock the `userService` hook

2024-05-01 07:13 UTC, khytrykv commented on tests/unit/components/loader/Loader.spec.jsx
But we don't use the `userService` in this component. Why should I mock it?

2024-05-01 15:56 UTC, vlad-khrychov approved these changes

2024-05-01 15:56 UTC, vlad-khrychov commented on tests/unit/components/loader/Loader.spec.jsx
Yes, sorry, my mistake

2024-05-01 19:38 UTC, merged