Add tests for Categories page
Space2Study-UA-1156/Client-01 pull request #151
Opened 2024-04-30 16:15 UTC by khytrykv

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/40d7e52c-9029-4f76-bbcb-08f1ebbe485f)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/3a8491c7-1164-45c6-8d97-07c114a5335d)

2024-04-30 16:20 UTC, YaroslavChuiko approved these changes

2024-04-30 17:14 UTC, YaroslavLys approved these changes

2024-04-30 18:02 UTC, holus-bolus approved these changes

2024-05-01 06:48 UTC, vlad-khrychov requested changes
Mock `PageWrapper` component and use `renderWithProviders` from '~tests/test-utils'.

2024-05-01 15:55 UTC, vlad-khrychov approved these changes
Before merging, check if everything works fine with the new version of vitest

2024-05-01 19:40 UTC, merged