Feature/139/sp 2 implement general info step
Space2Study-UA-1156/Client-01 pull request #169
Opened 2024-05-02 12:21 UTC by holus-bolus

Implemented the General info step

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/8a24cfc9-82f9-4794-bba3-88d2f92ca0bf)

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/958a7e69-b257-408c-8b30-cd665628d42b)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/027eec80-a982-44cb-9e6f-d8398cb6c296)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/ac8a21e9-f649-43ca-9c08-843dcd27542e)

2024-05-02 15:22 UTC, OlhaOvsiienko approved these changes

2024-05-03 07:18 UTC, YaroslavChuiko approved these changes

2024-05-03 07:26 UTC, khytrykv commented
https://www.figma.com/file/1NqYJ5oaby8tlU7zLQBOja/MVPSpace2Study-(Students)?type=design&node-id=9553-43449&mode=design&t=jxV51oMCSbTqgIty-0
Please adjust styles according to the mockup (space between inputs, etc.)

2024-05-03 07:37 UTC, khytrykv approved these changes

2024-05-03 08:02 UTC, voloshkin-v approved these changes

2024-05-03 08:33 UTC, vlad-khrychov requested changes
Fix errors from linter first. Also, create the separate tasks for items that was not implemented in this PR (add links to them):
- tests
- fetching cities
- fetching First name and Last name
- discuss with the team whether the check box is mandatory so that the user is over 18 years old (as a product owner I want to see check box).

2024-05-03 08:33 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +    setMessage(event.target.value.slice(0, 70))
save `70`  in a const.

2024-05-07 14:13 UTC, merged