Feature/184/sp 1 expand the functionality for the general info step
Space2Study-UA-1156/Client-01 pull request #185
Opened 2024-05-06 05:47 UTC by holus-bolus

Added the countries and cities fetching to the component

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/c020b3c9-d38c-42a4-af28-dcdb0448bcaa)

2024-05-06 06:59 UTC, khytrykv commented on .gitignore
> +.env.local
Do we need the duplicate here?

2024-05-06 07:02 UTC, holus-bolus commented on .gitignore
> +.env.local
It's strange, I deleted it.

2024-05-06 07:36 UTC, khytrykv commented on src/redux/reducer.js
> +      state.isFirstLogin = true
+

2024-05-06 07:36 UTC, khytrykv commented on tests/unit/containers/how-it-works/HowItWorks.spec.jsx
> +  it.skip('should change info by clicking on switch', () => {
Do we need it?

2024-05-06 17:23 UTC, YaroslavChuiko approved these changes

2024-05-06 19:54 UTC, OlhaOvsiienko approved these changes

2024-05-07 07:13 UTC, YaroslavLys approved these changes

2024-05-07 11:19 UTC, vlad-khrychov requested changes
Please save only necessary files for this PR, do not any additional logic. Also, think that you linked the wrong issue.
If we talk about creating only mockup:
 - create `GeneralInfoStep` component and all additional child components. 
 - For autocomplete use the mocked countries and cites (it may be one country and one city),
 - rewrite tests if they fell after changes
 - in context add only logic about saving and obtaining data from your step (if it possible do not rename variables).
 - Use MUI component and one code-style for styling them.

2024-05-07 11:19 UTC, vlad-khrychov commented on .vscode/settings.json
Remove it from PR unless agreed with the team.

2024-05-07 11:19 UTC, vlad-khrychov commented on src/components/user-steps-wrapper/UserStepsWrapper.jsx
Can we also discard this changes?

2024-05-07 11:19 UTC, vlad-khrychov commented on src/redux/reducer.js
discard changes

2024-05-07 11:19 UTC, vlad-khrychov commented on tests/unit/containers/how-it-works/HowItWorks.spec.jsx
> +  it.skip('should change info by clicking on switch', () => {
I agree with @khytrykv fix this test or write a new one.

2024-05-07 11:19 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/interfaces/IFormSection.ts
> +  errors: Record<string, unknown>
`unknown` is not much better than `any`.

2024-05-07 11:19 UTC, vlad-khrychov commented on tests/unit/components/step-wrapper/StepWrapper.spec.jsx
Return test or write a new one

2024-05-07 11:19 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/SelectGroup.tsx
> +    >
Why we use `div` not `Box`?

2024-05-07 14:27 UTC, closed without merging