Feature/174/categories results not found
Space2Study-UA-1156/Client-01 pull request #191
Opened 2024-05-06 17:34 UTC by OlhaOvsiienko

2024-05-07 06:56 UTC, YaroslavChuiko approved these changes

2024-05-07 07:13 UTC, YaroslavLys approved these changes

2024-05-07 07:31 UTC, holus-bolus approved these changes

2024-05-07 12:07 UTC, vlad-khrychov requested changes

2024-05-07 12:07 UTC, vlad-khrychov commented on tests/unit/containers/categories-results-not-found/CategoriesResultsNotFound.spec.jsx
Mock child components `ImgTitleDescription` and `AppButton`.

2024-05-10 10:07 UTC, OlhaOvsiienko commented on tests/unit/containers/categories-results-not-found/CategoriesResultsNotFound.spec.jsx
Child components ImgTitleDescription and AppButton are mocked.

2024-05-10 11:32 UTC, YaroslavChuiko approved these changes

2024-05-10 12:57 UTC, YaroslavLys approved these changes

2024-05-10 15:51 UTC, holus-bolus approved these changes

2024-05-13 19:30 UTC, vlad-khrychov approved these changes

2024-05-13 20:52 UTC, merged