Add unit tests for the subjects step
Space2Study-UA-1156/Client-01 pull request #208
Opened 2024-05-09 08:57 UTC by khytrykv

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/59e94972-e01c-465e-a92e-11caad60e99d)

2024-05-09 11:33 UTC, OlhaOvsiienko approved these changes

2024-05-09 15:29 UTC, YaroslavChuiko approved these changes

2024-05-09 16:54 UTC, holus-bolus approved these changes

2024-05-10 07:29 UTC, vlad-khrychov requested changes

2024-05-10 07:29 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/subjects-step/SubjectStep.spec.jsx
Add test that user can not add the similar subject twice. For this you should rewrite mock of `step-context` or delete it and mock only hooks for obtaining data from context.

2024-05-10 08:18 UTC, khytrykv commented on tests/unit/containers/tutor-home-page/subjects-step/SubjectStep.spec.jsx
Added

2024-05-13 19:29 UTC, vlad-khrychov approved these changes

2024-05-13 19:50 UTC, merged