implement category icon service
Space2Study-UA-1156/Client-01 pull request #212
Opened 2024-05-10 09:30 UTC by YaroslavChuiko

- [ ]  Implement a service for selecting category icons by their names

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/4ef44b6c-6b39-4524-aab9-a73b45426e21)

2024-05-10 10:08 UTC, OlhaOvsiienko approved these changes

2024-05-10 12:54 UTC, YaroslavLys approved these changes

2024-05-13 07:05 UTC, holus-bolus approved these changes

2024-05-13 20:01 UTC, vlad-khrychov requested changes

2024-05-13 20:01 UTC, vlad-khrychov commented on src/services/category-icon-service.ts
> +): typeof CATEGORY_ICONS[IconKey] => {
add import `import { SvgIconComponent } from '@mui/icons-material'`
```suggestion
): SvgIconComponent => {
```

2024-05-13 20:01 UTC, vlad-khrychov commented on src/services/category-icon-service.ts
> +}
```suggestion
export const getCategoryIcon = (
  category: IconKey
): SvgIconComponent => {
  return CATEGORY_ICONS[category] || CATEGORY_ICONS['LanguageIcon']
}
```

2024-05-13 20:01 UTC, vlad-khrychov commented on tests/unit/services/category-icon-service.spec.js
> +  it('should return LanguageIcon', () => {
```suggestion
  it('should return LanguageIcon for invalid icon name', () => {
```

2024-05-13 20:01 UTC, vlad-khrychov commented on src/services/category-icon-service.ts
> +}
I do not think that we need this function.

2024-05-14 09:13 UTC, vlad-khrychov approved these changes

2024-05-14 09:36 UTC, merged