Create component for rich text editor
Space2Study-UA-1156/Client-01 pull request #300
Opened 2024-05-27 12:23 UTC by khytrykv

Example of usage:
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/9ac410d6-48a0-450f-bbef-fc461ad7ac99)
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/29426272/ca630ee4-0243-4d50-b1d2-245637acbde3)

2024-05-27 12:26 UTC, YaroslavChuiko approved these changes

2024-05-27 12:43 UTC, voloshkin-v approved these changes

2024-05-27 12:52 UTC, OlhaOvsiienko approved these changes

2024-05-27 17:33 UTC, vlad-khrychov requested changes

2024-05-27 17:33 UTC, vlad-khrychov commented on src/components/app-rich-text-editor/AppRichTextEditor.jsx
> +      apiKey='dn0tzus4or3d0n2s2p68n9wsuxw75cv0m8pvfj2ygh9twrv6'
Hide `apiKey` in environment variables

2024-05-28 07:04 UTC, khytrykv commented on src/components/app-rich-text-editor/AppRichTextEditor.jsx
> +      apiKey='dn0tzus4or3d0n2s2p68n9wsuxw75cv0m8pvfj2ygh9twrv6'
Done. Thanks)

2024-05-28 07:13 UTC, vlad-khrychov approved these changes

2024-05-28 07:25 UTC, merged