Feature/291/sp 2 implement subjects page
Space2Study-UA-1156/Client-01 pull request #320
Opened 2024-05-30 13:30 UTC by holus-bolus

Implemented the drawer with the subjects adding.

https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/30f62dee-915d-48bd-9bf6-8fc6e9a0803b

2024-05-30 13:48 UTC, OlhaOvsiienko approved these changes

2024-05-30 14:17 UTC, YaroslavChuiko requested changes
### App:
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/28cb7142-6925-4f06-a3f7-7dd5a32f5ce4)

### Figma:
![image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/1ce7106c-f893-4b12-961b-af85063bb334)

I think we need to fix styles here

2024-05-31 05:48 UTC, holus-bolus commented
> ### App:
> ![image](https://private-user-images.githubusercontent.com/32570823/335219336-28cb7142-6925-4f06-a3f7-7dd5a32f5ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzQ2NjMsIm5iZiI6MTcxNzEzNDM2MywicGF0aCI6Ii8zMjU3MDgyMy8zMzUyMTkzMzYtMjhjYjcxNDItNjkyNS00ZjA2LWEzZjctN2RkNWEzMmY1Y2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YzI0M2U1ZjlkNzAyZGM1Njk5MzRiM2M2MjQ5NWIwZGY0OWQyNzcxNzkyNGI3Y2NkNGQwZTc4MTQ1OTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vnxRD8__Ek_gljihxEqkhNYy0IrXeFsVwBFVQHbPmkY)
> 
> ### Figma:
> ![image](https://private-user-images.githubusercontent.com/32570823/335220827-1ce7106c-f893-4b12-961b-af85063bb334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzQ2NjMsIm5iZiI6MTcxNzEzNDM2MywicGF0aCI6Ii8zMjU3MDgyMy8zMzUyMjA4MjctMWNlNzEwNmMtZjg5My00YjEyLTk2MWItYWY4NTA2M2JiMzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5Nzg2OWMxMTIyNTdiNjE5MTQzNmE2OWI5NGQ2ODkzOGJkZjEwMzIzNjI0OGQwYmJlMmYyZDE3ZWJhOGIwY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YnYLtedIJzSg5SnmFKtAjTi5GsUjlh8IPs61tDF2UDQ)
> 
> I think we need to fix styles here

![image](https://github.com/Space2Study-UA-1156/Client-01/assets/93076661/79a12a98-5479-441c-9136-12d715ea16cd)

2024-05-31 10:40 UTC, YaroslavChuiko approved these changes

2024-05-31 11:22 UTC, voloshkin-v approved these changes

2024-05-31 11:26 UTC, merged